# Generated by Django 4.2.1 on 2023-06-07 05:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('apps_froze', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='froze',
            name='nomer_dogovora',
            field=models.CharField(blank=True, default='', max_length=20, null=True, verbose_name='Номер договора'),
        ),
    ]
