# Generated by Django 4.2.1 on 2023-05-22 12:43

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('apps_froze', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='DogovorIndi',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('published', models.DateTimeField(default=django.utils.timezone.now, verbose_name='Дата Создания')),
                ('passport_familiya', models.CharField(blank=True, db_index=True, default='', max_length=200)),
                ('passport_imya', models.CharField(blank=True, db_index=True, default='', max_length=200)),
                ('passport_otchestvo', models.CharField(blank=True, db_index=True, default='', max_length=200)),
                ('passport_birthday_date', models.DateField(blank=True, default=None, null=True)),
                ('passport_birthday_place', models.CharField(blank=True, default='', max_length=200, null=True)),
                ('passport_seria', models.CharField(blank=True, default=None, max_length=4, null=True)),
                ('passport_nomer', models.CharField(blank=True, default=None, max_length=6, null=True)),
                ('passport_kem_vydan', models.CharField(blank=True, default='', max_length=200, null=True)),
                ('passport_kogda_vydan', models.DateField(blank=True, default=None, null=True)),
                ('passport_kp', models.CharField(blank=True, default=None, max_length=7, null=True)),
                ('adres_propiski', models.CharField(blank=True, default='', max_length=200, null=True)),
                ('adres_ustanovki', models.CharField(blank=True, default='', max_length=200, null=True)),
                ('vsego_k_oplate', models.PositiveIntegerField(blank=True, default=None, null=True)),
                ('oplata_predoplata_rub', models.PositiveIntegerField(blank=True, default=None, null=True)),
                ('installment_plan', models.PositiveIntegerField(blank=True, default=None, null=True)),
                ('naimenov_soputstv_izdeliy', models.CharField(blank=True, default='', max_length=200, null=True)),
                ('summa_za_soputstv_uslugi', models.PositiveIntegerField(blank=True, default=None, null=True)),
                ('stoimost_dostavki_vne_ufa', models.PositiveIntegerField(blank=True, default=None, null=True)),
                ('data_podpisaniya', models.DateField(blank=True, default=None, null=True)),
                ('srok_ispolneniya_rabot', models.PositiveSmallIntegerField(blank=True, default=None, null=True)),
                ('tip_dogovora', models.CharField(blank=True, choices=[('izgotovlenie_2023_06_mebeli_ip_frolov', 'Изготовление мебели | ИП Фролов'), ('izgotovlenie_2023_06_mebeli_ip_bagautdinov', 'Изготовление мебели | ИП Багаутдинов'), ('izgotovlenie_2023_06_mebeli_ip_sadykov', 'Изготовление мебели | ИП Садыков'), ('izgotovlenie_2023_06_mebeli_ip_hafizov', 'Изготовление мебели | ИП Хафизов')], db_index=True, default=0, max_length=100, null=True, verbose_name='Тип договора')),
                ('nomer_dogovora', models.CharField(blank=True, default='', max_length=20, null=True, verbose_name='Номер договора')),
                ('tip_opisanie_izdeliya', models.CharField(blank=True, default='', max_length=500, null=True)),
                ('doverennye_lica', models.CharField(blank=True, default='', max_length=500, null=True)),
                ('doverennye_lica_telefony', models.CharField(blank=True, default='', max_length=500, null=True)),
                ('nachalo_rabot_data', models.DateField(blank=True, default=None, null=True)),
                ('okonchanie_rabot_data', models.DateField(blank=True, default=None, null=True)),
                ('tovarny_chek_tehnika', models.TextField(blank=True, default='', null=True)),
                ('uslugi_po_podklyucheniyu_tehniki', models.TextField(blank=True, default='', null=True)),
                ('work_performed_list', models.TextField(blank=True, default='', null=True)),
                ('list_of_work_installation', models.TextField(blank=True, default='', null=True)),
                ('mygkaya_mebel_prilozhenie', models.TextField(blank=True, default='', null=True)),
                ('technics_sroki_dostavki_tehniki', models.PositiveIntegerField(blank=True, default=None, null=True)),
                ('technics_sroki_dostavki_tehniki_v_dnyah', models.PositiveIntegerField(blank=True, default=None, null=True)),
                ('drugoy_dogovor', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='apps_dogovora.dogovorindi')),
                ('froze', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='apps_froze.froze', verbose_name='Заявка')),
            ],
            options={
                'verbose_name': 'Договор',
                'verbose_name_plural': 'Договоры',
                'db_table': 'dogovora',
            },
        ),
    ]
