# Generated by Django 4.2.1 on 2023-06-02 06:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('apps_dogovora', '0002_alter_dogovorindi_tip_dogovora_dogovorentry'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='dogovorentry',
            name='author',
        ),
    ]
