# Generated by Django 4.2.1 on 2023-06-02 08:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('apps_dogovora', '0003_remove_dogovorentry_author'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='dogovorentry',
            name='passport_birthday_date',
        ),
        migrations.RemoveField(
            model_name='dogovorentry',
            name='passport_birthday_place',
        ),
        migrations.RemoveField(
            model_name='dogovorentry',
            name='passport_kem_vydan',
        ),
        migrations.RemoveField(
            model_name='dogovorentry',
            name='passport_kogda_vydan',
        ),
        migrations.RemoveField(
            model_name='dogovorentry',
            name='passport_kp',
        ),
        migrations.RemoveField(
            model_name='dogovorentry',
            name='passport_nomer',
        ),
        migrations.RemoveField(
            model_name='dogovorentry',
            name='passport_seria',
        ),
    ]
